### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by georgepapas** [unixsurfer/anycast_healthchecker#17]
Trying to run main.py or healthchecker.py after installing via pip or a debian package gives the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/anycast_healthchecker/main.py", line 31, in <module>
    from anycast_healthchecker import (DEFAULT_OPTIONS, PROGRAM_NAME, __version__,
  File "/usr/local/lib/python2.7/dist-packages/anycast_healthchecker/healthchecker.py", line 7, in <module>
    from queue import Queue
ImportError: No module named queue
```

Are there any deps that need to be installed prior? Have I missed something in the docs? 

Cheers

**Comment by georgepapas** [comment]
solved this by using venv, python3 and pip3
